### ISSUE TITLE
Remove redundant license comments in built files.

### ISSUE THREAD

**Issue by blzaugg** [liferay/liferay-theme-tasks#47]
Expected output:

```css
@charset "UTF-8";
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
@import url(font_lato.css);
.loading-animation, .loadingmask-message .loadingmask-message-content {
  animation: loading-animation 1.7s infinite ease;
  border-radius: 50%;
  clear: both;
  font-size: 64px;
  height: 1em;
  margin: 1em auto;
  overflow: hidden;
  position: relative;
  transform: translateZ(0);
  width: 1em; }
```

Actual output:

```css
@charset "UTF-8";
/*
  Note: this file was generated by the `gulp upgrade` task and provides compass
  mixins that may have been used in your 6.2 theme. It is both safe and
  recommended to remove this file if you are not using these mixins.

  This file will be included anywhere `@import "bourbon";` is imported.
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
/**
* Lexicon 1.0.19
*
* Copyright 2017, Liferay, Inc.
* All rights reserved.
* MIT license
*/
@import url(font_lato.css);
.loading-animation, .loadingmask-message .loadingmask-message-content {
  animation: loading-animation 1.7s infinite ease;
  border-radius: 50%;
  clear: both;
  font-size: 64px;
  height: 1em;
  margin: 1em auto;
  overflow: hidden;
  position: relative;
  transform: translateZ(0);
  width: 1em; }
```
